version: "3"
services:
  react_app:
    build: ./front-end
    container_name: react_app
    volumes:
      - build_react:/var/www/html
    depends_on:
      - app_node

  banco:
    image: postgres
    environment:
      - POSTGRES_DATABASE=cachorrada
      - POSTGRES_HOST_AUTH_METHOD=trust
    container_name: banco
    ports:
      - 2345:5432
    env_file:
      - ./back-end/.env
    volumes:
      - volume_banco:/var/lib/postgresql/data

  app_node:
    build: ./back-end
    container_name: app_node
    ports:
      - 4000:4000
    env_file:
      - ./back-end/.env
    volumes:
      - ./back-end/.env
      - /usr/src/node_modules
    entrypoint: dockerize -wait tcp://banco:5432 -timeout 20s docker-entrypoint.sh
    command: "npx prisma migrate dev && npx prisma db seed && npm run dev"
    depends_on:
      - banco

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - react_app

volumes:
  build_react:
  volume_banco:
